[package]
name = "gatekeeper"
version = "0.1.0"
authors = ["Marius <marius@twostairs.com>"]
edition = "2018"

[dependencies]
hyper-reverse-proxy = "0.4"
hyper = "0.12"
futures = "0.1"
frank_jwt = "3.1.0"
serde_json = "1.0.39"
lazy_static = "1.3.0"
